base:
  project: wine.project
  random_state: 42
  target_col: TARGET

data_source:
  s3_source: data_given\wine.csv

load_data:
  raw_dataset_csv: data\raw\wine.csv

split_data:
  train_path: data\processed\wine.csv
  test_path: data\processed\wine.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
    alpha: 0.88
    l1_ratio: 0.89

model_dir: saved_models



